/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Expandomatic
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
function mk(line, ch) {
  return { line, ch };
}
function rng(sl, sc, el, ec) {
  return { anchor: mk(sl, sc), head: mk(el, ec) };
}
function posLt(a, b) {
  return a.line < b.line || a.line === b.line && a.ch < b.ch;
}
function posEq(a, b) {
  return a.line === b.line && a.ch === b.ch;
}
function posMin(a, b) {
  return posLt(a, b) ? a : b;
}
function posMax(a, b) {
  return posLt(a, b) ? b : a;
}
function strictlyContains(candidate, from, to) {
  const cf = posMin(candidate.anchor, candidate.head);
  const ct = posMax(candidate.anchor, candidate.head);
  const fge = !posLt(from, cf);
  const tle = !posLt(ct, to);
  const wider = posLt(cf, from) || posLt(to, ct);
  return fge && tle && wider;
}
function headingLevel(line) {
  const m = line.match(/^(#{1,6}) /);
  return m ? m[1].length : 0;
}
function bulletMatch(line) {
  return line.match(/^(\s*)([-*+]|\d+\.)\s+/);
}
function bulletIndentLevel(line) {
  const m = bulletMatch(line);
  return m ? m[1].length : -1;
}
function bulletContentOffset(line) {
  const m = bulletMatch(line);
  return m ? m[0].length : -1;
}
function findSentenceBoundaries(text) {
  var _a, _b;
  const boundaries = [0];
  let i = 0;
  while (i < text.length) {
    const ch = text[i];
    if (ch === "." || ch === "!" || ch === "?") {
      let j = i + 1;
      while (j < text.length && ".!?".includes(text[j]))
        j++;
      while (j < text.length && /["'\)\]>]/.test(text[j]))
        j++;
      if (j >= text.length || /[ \t\n]/.test(text[j])) {
        let k = j;
        while (k < text.length && text[k] === " ")
          k++;
        const next = k < text.length ? text[k] : "";
        if (next === "" || /[A-Z]/.test(next) || /[-*#\[>!]/.test(next)) {
          const wordBefore = (_b = (_a = text.slice(0, i).match(/\S+$/)) == null ? void 0 : _a[0]) != null ? _b : "";
          if (ch === "." && wordBefore.length <= 2 && /^[A-Za-z]$/.test(wordBefore)) {
            i++;
            continue;
          }
          if (k > 0)
            boundaries.push(k);
          i = k;
          continue;
        }
      }
    }
    i++;
  }
  if (boundaries[boundaries.length - 1] !== text.length) {
    boundaries.push(text.length);
  }
  return boundaries;
}
function findSentence(text, fromOff, toOff) {
  const bounds = findSentenceBoundaries(text);
  if (bounds.length < 2)
    return null;
  for (let i = 0; i < bounds.length - 1; i++) {
    if (bounds[i] <= fromOff && bounds[i + 1] >= toOff) {
      return { start: bounds[i], end: bounds[i + 1] };
    }
  }
  let start = -1, end = -1;
  for (let i = 0; i < bounds.length - 1; i++) {
    if (bounds[i + 1] > fromOff && bounds[i] < toOff) {
      if (start < 0)
        start = bounds[i];
      end = bounds[i + 1];
    }
  }
  if (start >= 0)
    return { start, end };
  return null;
}
var Expandomatic = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.selStack = [];
    this.lastSet = null;
  }
  async onload() {
    this.addCommand({
      id: "expand-selection",
      name: "Expand Selection",
      editorCallback: (editor) => this.expand(editor)
    });
    this.addCommand({
      id: "shrink-selection",
      name: "Shrink Selection",
      editorCallback: (editor) => this.shrink(editor)
    });
  }
  onunload() {
  }
  rangeEq(a, b) {
    return posEq(posMin(a.anchor, a.head), posMin(b.anchor, b.head)) && posEq(posMax(a.anchor, a.head), posMax(b.anchor, b.head));
  }
  expand(editor) {
    var _a;
    const sels = editor.listSelections();
    if (!sels.length)
      return;
    const sel = sels[0];
    const cur = { anchor: sel.anchor, head: sel.head };
    if (this.lastSet !== null && !this.rangeEq(cur, this.lastSet)) {
      this.selStack = [];
      this.lastSet = null;
    }
    const from = posMin(cur.anchor, cur.head);
    const to = posMax(cur.anchor, cur.head);
    if (posEq(from, to)) {
      const target = (_a = this.nearestWord(editor, from)) != null ? _a : this.nearestSection(editor, from);
      if (target) {
        this.selStack.push(cur);
        editor.setSelection(target.anchor, target.head);
        this.lastSet = target;
      }
      return;
    }
    const ctx = this.context(editor, from, to);
    const candidates = this.expansions(editor, ctx, from, to);
    for (const candidate of candidates) {
      if (candidate != null && strictlyContains(candidate, from, to)) {
        this.selStack.push(cur);
        editor.setSelection(candidate.anchor, candidate.head);
        this.lastSet = { anchor: candidate.anchor, head: candidate.head };
        return;
      }
    }
  }
  shrink(editor) {
    const sels = editor.listSelections();
    if (!sels.length)
      return;
    const sel = sels[0];
    const cur = { anchor: sel.anchor, head: sel.head };
    if (this.lastSet === null || !this.rangeEq(cur, this.lastSet) || this.selStack.length === 0) {
      this.selStack = [];
      this.lastSet = null;
      return;
    }
    const prev = this.selStack.pop();
    editor.setSelection(prev.anchor, prev.head);
    this.lastSet = prev;
  }
  // ── Context detection ───────────────────────────────────────────────────
  context(editor, from, to) {
    const line = editor.getLine(from.line);
    if (/^\s*\|/.test(line))
      return "table";
    if (this.inFencedCode(editor, from))
      return "code";
    if (this.inEquation(editor, from))
      return "equation";
    if (!posEq(from, to) && from.line === to.line) {
      const inside = mk(from.line, from.ch + 1);
      if (inside.ch <= to.ch && this.inEquation(editor, inside))
        return "equation";
    }
    if (bulletMatch(line))
      return "list";
    return "prose";
  }
  inFencedCode(editor, pos) {
    let open = false;
    for (let i = 0; i < pos.line; i++) {
      if (/^(`{3,}|~{3,})/.test(editor.getLine(i)))
        open = !open;
    }
    return open;
  }
  inBlockEquation(editor, pos) {
    let open = false;
    for (let i = 0; i < pos.line; i++) {
      if (editor.getLine(i).trim() === "$$")
        open = !open;
    }
    return open;
  }
  inEquation(editor, pos) {
    if (this.inBlockEquation(editor, pos))
      return true;
    const line = editor.getLine(pos.line);
    let count = 0;
    for (let i = 0; i < pos.ch; i++) {
      if (line[i] === "$" && (i === 0 || line[i - 1] !== "$") && (i + 1 >= line.length || line[i + 1] !== "$"))
        count++;
    }
    return count % 2 === 1;
  }
  // ── Expansion lists ─────────────────────────────────────────────────────
  expansions(editor, ctx, from, to) {
    switch (ctx) {
      case "table":
        return [
          this.wordAt(editor, from),
          this.tableCell(editor, from),
          this.tableRow(editor, from),
          this.tableAll(editor, from),
          this.wholeDoc(editor)
        ];
      case "code":
        return [
          this.wordAt(editor, from),
          this.codeLine(editor, from),
          this.codeBlock(editor, from),
          this.wholeDoc(editor)
        ];
      case "equation":
        if (this.inBlockEquation(editor, from)) {
          return [
            this.wordAt(editor, from),
            this.eqTerm(editor, from),
            this.eqLine(editor, from),
            this.eqBlock(editor, from),
            this.wholeDoc(editor)
          ];
        }
        return [
          this.wordAt(editor, from),
          this.eqTerm(editor, from),
          this.inlineEqBlock(editor, from),
          this.eqLine(editor, from),
          this.wholeDoc(editor)
        ];
      case "list": {
        const ancestors = this.bulletAncestorExpansions(editor, from.line);
        return [
          this.wordAt(editor, from),
          this.urlAt(editor, from, to),
          this.bulletSentence(editor, from, to),
          this.bulletContent(editor, from),
          this.bulletWithChildren(editor, from.line),
          ...ancestors,
          this.paragraph(editor, from),
          this.section(editor, from, to),
          this.wholeDoc(editor)
        ];
      }
      default:
        return [
          this.wordAt(editor, from),
          this.urlAt(editor, from, to),
          this.sentence(editor, from, to),
          this.paragraph(editor, from),
          this.section(editor, from, to),
          this.wholeDoc(editor)
        ];
    }
  }
  // ── Atomic expansion methods ────────────────────────────────────────────
  wordAt(editor, pos) {
    const r = editor.wordAt(pos);
    return r ? { anchor: r.from, head: r.to } : null;
  }
  nearestWord(editor, pos) {
    const w = editor.wordAt(pos);
    if (w)
      return { anchor: w.from, head: w.to };
    const line = editor.getLine(pos.line);
    for (let d = 1; d <= line.length; d++) {
      const li = pos.ch - d;
      if (li >= 0 && /\w/.test(line[li])) {
        const hit = editor.wordAt(mk(pos.line, li));
        if (hit)
          return { anchor: hit.from, head: hit.to };
      }
      const ri = pos.ch + d;
      if (ri < line.length && /\w/.test(line[ri])) {
        const hit = editor.wordAt(mk(pos.line, ri));
        if (hit)
          return { anchor: hit.from, head: hit.to };
      }
    }
    return null;
  }
  nearestSection(editor, pos) {
    const lineCount = editor.lineCount();
    const headings = [];
    for (let i = 0; i < lineCount; i++) {
      const lv = headingLevel(editor.getLine(i));
      if (lv > 0)
        headings.push({ line: i, level: lv });
    }
    if (headings.length === 0)
      return null;
    let nearestIdx = 0;
    let nearestDist = Math.abs(headings[0].line - pos.line);
    for (let i = 1; i < headings.length; i++) {
      const d = Math.abs(headings[i].line - pos.line);
      if (d < nearestDist) {
        nearestDist = d;
        nearestIdx = i;
      }
    }
    const h = headings[nearestIdx];
    let endLine = lineCount - 1;
    for (let hj = nearestIdx + 1; hj < headings.length; hj++) {
      if (headings[hj].level <= h.level) {
        endLine = headings[hj].line - 1;
        break;
      }
    }
    while (endLine > h.line && editor.getLine(endLine).trim() === "")
      endLine--;
    return rng(h.line, 0, endLine, editor.getLine(endLine).length);
  }
  // Prose: URL
  urlAt(editor, from, to) {
    const line = editor.getLine(from.line);
    const re = /https?:\/\/[^\s)\]>"'`]+/g;
    let m;
    while ((m = re.exec(line)) !== null) {
      const s = m.index, e = s + m[0].length;
      if (s <= from.ch && e >= to.ch && !(s === from.ch && e === to.ch)) {
        return rng(from.line, s, from.line, e);
      }
    }
    return null;
  }
  // Prose: sentence
  sentence(editor, from, to) {
    const pr = this.paragraphBounds(editor, from.line);
    const base = mk(pr.start, 0);
    const text = editor.getRange(base, mk(pr.end, editor.getLine(pr.end).length));
    const fromOff = this.toOffset(editor, from, pr.start);
    const toOff = this.toOffset(editor, to, pr.start);
    const sent = findSentence(text, fromOff, toOff);
    if (!sent)
      return null;
    const anchor = this.fromOffset(editor, sent.start, pr.start);
    const head = this.fromOffset(editor, sent.end, pr.start);
    if (posEq(anchor, from) && posEq(head, to))
      return null;
    return { anchor, head };
  }
  // Prose: paragraph (blank-line bounded)
  paragraph(editor, from) {
    const pr = this.paragraphBounds(editor, from.line);
    return rng(pr.start, 0, pr.end, editor.getLine(pr.end).length);
  }
  // Prose: smallest section that strictly contains [from, to], then next larger, etc.
  // Because strictlyContains is checked by the caller, a single method suffices —
  // each call will naturally find the next larger section.
  section(editor, from, to) {
    const lineCount = editor.lineCount();
    const headings = [];
    for (let i = 0; i < lineCount; i++) {
      const lv = headingLevel(editor.getLine(i));
      if (lv > 0)
        headings.push({ line: i, level: lv });
    }
    if (headings.length === 0)
      return null;
    let best = null;
    let bestSize = Infinity;
    for (let hi = 0; hi < headings.length; hi++) {
      const h = headings[hi];
      let endLine = lineCount - 1;
      for (let hj = hi + 1; hj < headings.length; hj++) {
        if (headings[hj].level <= h.level) {
          endLine = headings[hj].line - 1;
          break;
        }
      }
      while (endLine > h.line && editor.getLine(endLine).trim() === "")
        endLine--;
      const candidate = rng(h.line, 0, endLine, editor.getLine(endLine).length);
      if (strictlyContains(candidate, from, to)) {
        const size = (endLine - h.line) * 1e4 + editor.getLine(endLine).length;
        if (size < bestSize) {
          best = candidate;
          bestSize = size;
        }
      }
    }
    return best;
  }
  // ── List / bullet ───────────────────────────────────────────────────────
  bulletSentence(editor, from, to) {
    const line = editor.getLine(from.line);
    const offset = bulletContentOffset(line);
    if (offset < 0)
      return null;
    const text = line.slice(offset);
    const fromOff = Math.max(0, from.ch - offset);
    const toOff = to.line === from.line ? Math.max(0, to.ch - offset) : text.length;
    const sent = findSentence(text, fromOff, toOff);
    if (!sent)
      return null;
    const anchor = mk(from.line, offset + sent.start);
    const head = mk(from.line, offset + sent.end);
    if (posEq(anchor, from) && posEq(head, to))
      return null;
    return { anchor, head };
  }
  bulletContent(editor, pos) {
    const line = editor.getLine(pos.line);
    const offset = bulletContentOffset(line);
    if (offset < 0)
      return null;
    return rng(pos.line, offset, pos.line, line.length);
  }
  bulletWithChildren(editor, bulletLine) {
    var _a, _b;
    const lc = editor.lineCount();
    const line = editor.getLine(bulletLine);
    const myIndent = bulletIndentLevel(line);
    if (myIndent < 0)
      return null;
    let end = bulletLine;
    for (let i = bulletLine + 1; i < lc; i++) {
      const l = editor.getLine(i);
      if (l.trim() === "")
        break;
      const lineIndent = (_b = (_a = l.match(/^(\s*)/)) == null ? void 0 : _a[1].length) != null ? _b : 0;
      const bIndent = bulletIndentLevel(l);
      if (bIndent >= 0 && bIndent <= myIndent)
        break;
      if (bIndent < 0 && lineIndent <= myIndent)
        break;
      end = i;
    }
    return rng(bulletLine, 0, end, editor.getLine(end).length);
  }
  bulletAncestorExpansions(editor, bulletLine) {
    const line = editor.getLine(bulletLine);
    let myIndent = bulletIndentLevel(line);
    if (myIndent < 0)
      return [];
    const results = [];
    for (let i = bulletLine - 1; i >= 0; i--) {
      const l = editor.getLine(i);
      if (l.trim() === "")
        break;
      const bIndent = bulletIndentLevel(l);
      if (bIndent >= 0 && bIndent < myIndent) {
        results.push(this.bulletWithChildren(editor, i));
        myIndent = bIndent;
        if (myIndent === 0)
          break;
      }
    }
    return results;
  }
  wholeDoc(editor) {
    const last = editor.lineCount() - 1;
    return rng(0, 0, last, editor.getLine(last).length);
  }
  // ── Table ───────────────────────────────────────────────────────────────
  tableCell(editor, pos) {
    const line = editor.getLine(pos.line);
    let s = pos.ch, e = pos.ch;
    while (s > 0 && line[s - 1] !== "|")
      s--;
    while (e < line.length && line[e] !== "|")
      e++;
    return rng(pos.line, s, pos.line, e);
  }
  tableRow(editor, pos) {
    return rng(pos.line, 0, pos.line, editor.getLine(pos.line).length);
  }
  tableAll(editor, pos) {
    const lc = editor.lineCount();
    let s = pos.line, e = pos.line;
    while (s > 0 && /^\s*\|/.test(editor.getLine(s - 1)))
      s--;
    while (e < lc - 1 && /^\s*\|/.test(editor.getLine(e + 1)))
      e++;
    return rng(s, 0, e, editor.getLine(e).length);
  }
  // ── Code block ──────────────────────────────────────────────────────────
  codeLine(editor, pos) {
    return rng(pos.line, 0, pos.line, editor.getLine(pos.line).length);
  }
  codeBlock(editor, pos) {
    const lc = editor.lineCount();
    const fence = /^(`{3,}|~{3,})/;
    let s = pos.line, e = pos.line;
    while (s > 0 && !fence.test(editor.getLine(s)))
      s--;
    while (e < lc - 1 && !fence.test(editor.getLine(e)))
      e++;
    return rng(s, 0, e, editor.getLine(e).length);
  }
  // ── Equation ────────────────────────────────────────────────────────────
  inlineEqBlock(editor, pos) {
    const line = editor.getLine(pos.line);
    const isSingle = (i) => line[i] === "$" && (i === 0 || line[i - 1] !== "$") && (i + 1 >= line.length || line[i + 1] !== "$");
    let s = pos.ch - 1;
    while (s >= 0 && !isSingle(s))
      s--;
    if (s < 0)
      return null;
    let e = pos.ch;
    while (e < line.length && !isSingle(e))
      e++;
    if (e >= line.length)
      return null;
    return rng(pos.line, s, pos.line, e + 1);
  }
  eqTerm(editor, pos) {
    const line = editor.getLine(pos.line);
    const op = /[+\-*/=^,\s()\[\]{}\\$&|]/;
    let s = pos.ch, e = pos.ch;
    while (s > 0 && !op.test(line[s - 1]))
      s--;
    while (e < line.length && !op.test(line[e]))
      e++;
    return rng(pos.line, s, pos.line, e);
  }
  eqLine(editor, pos) {
    return rng(pos.line, 0, pos.line, editor.getLine(pos.line).length);
  }
  eqBlock(editor, pos) {
    const lc = editor.lineCount();
    const isDelim = (l) => editor.getLine(l).trim() === "$$";
    let s = pos.line, e = pos.line;
    while (s > 0 && !isDelim(s))
      s--;
    while (e < lc - 1 && !isDelim(e))
      e++;
    return rng(s, 0, e, editor.getLine(e).length);
  }
  // ── Paragraph / offset helpers ───────────────────────────────────────────
  paragraphBounds(editor, line) {
    const lc = editor.lineCount();
    if (headingLevel(editor.getLine(line)) > 0)
      return { start: line, end: line };
    let s = line, e = line;
    while (s > 0 && editor.getLine(s - 1).trim() !== "" && headingLevel(editor.getLine(s - 1)) === 0)
      s--;
    while (e < lc - 1 && editor.getLine(e + 1).trim() !== "" && headingLevel(editor.getLine(e + 1)) === 0)
      e++;
    return { start: s, end: e };
  }
  toOffset(editor, pos, startLine) {
    let off = 0;
    for (let i = startLine; i < pos.line; i++)
      off += editor.getLine(i).length + 1;
    return off + pos.ch;
  }
  fromOffset(editor, offset, startLine) {
    let rem = offset, line = startLine;
    while (true) {
      const len = editor.getLine(line).length;
      if (rem <= len)
        return mk(line, rem);
      rem -= len + 1;
      line++;
    }
  }
};

/* nosourcemap */