name: Deploy elliotwinkler.com
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  deploy-personal-site:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy elliotwinkler.com in preview mode
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.DEPLOY_PERSONAL_SITE_TOKEN }}
          # We have to dispatch the workflow, not call it, because the Vercel
          # secrets are in the site repo, not this repo
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'mcmire',
              repo: 'elliotwinkler.com',
              workflow_id: 'deploy-to-vercel.yml',
              ref: 'fix-deployment',
              inputs: {
                'vercel-environment': 'preview',
                'subrepo-name': context.repo.repo,
                'subrepo-ref': process.env.SUBREPO_REF,
                'subrepo-pull-request-number': process.env.PULL_REQUEST_NUMBER,
                'clone-subrepo-token': process.env.DEPLOY_PERSONAL_SITE_TOKEN,
                'update-deployment-status-token': process.env.DEPLOY_PERSONAL_SITE_TOKEN,
              }
            })
        env:
          DEPLOY_PERSONAL_SITE_TOKEN: ${{ secrets.DEPLOY_PERSONAL_SITE_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || 0 }}
          SUBREPO_REF: ${{ github.head_ref || github.ref_name }}
